.TH "src/draw.cpp" 3 "Thu Apr 5 2018" "COP290" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/draw.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <math\&.h>\fP
.br
\fC#include <QtCore>\fP
.br
\fC#include <QtGui>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include '\&.\&./lib/Vertex\&.cpp'\fP
.br
\fC#include 'TwoToThree\&.cpp'\fP
.br
\fC#include 'ThreeToTwo\&.cpp'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBPI\fP   3\&.1415926536"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define PI   3\&.1415926536"

.PP
Definition at line 7 of file draw\&.cpp\&.
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char * argv[])"

.PP
Definition at line 15 of file draw\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for COP290 from the source code\&.
