.TH "Point2D" 3 "Thu Apr 5 2018" "COP290" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Point2D \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBx\fP"
.br
.ti -1c
.RI "float \fBy\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 11 of file Vertex\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "float Point2D::x"

.PP
Definition at line 13 of file Vertex\&.cpp\&.
.SS "float Point2D::y"

.PP
Definition at line 14 of file Vertex\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for COP290 from the source code\&.
