.TH "src/ThreeToTwo.cpp" 3 "Thu Apr 5 2018" "COP290" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/ThreeToTwo.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <bits/stdc++\&.h>\fP
.br
\fC#include <armadillo>\fP
.br
\fC#include <limits>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBThree_To_Two\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for COP290 from the source code\&.
