.TH "Vertex2D" 3 "Thu Apr 5 2018" "COP290" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Vertex2D \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBlabel\fP"
.br
.ti -1c
.RI "float \fBx\fP"
.br
.ti -1c
.RI "float \fBy\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 4 of file Vertex\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "string Vertex2D::label"

.PP
Definition at line 6 of file Vertex\&.cpp\&.
.SS "float Vertex2D::x"

.PP
Definition at line 7 of file Vertex\&.cpp\&.
.SS "float Vertex2D::y"

.PP
Definition at line 8 of file Vertex\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for COP290 from the source code\&.
