.TH "lib/Vertex.cpp" 3 "Thu Apr 5 2018" "COP290" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/Vertex.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <bits/stdc++\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBVertex2D\fP"
.br
.ti -1c
.RI "struct \fBPoint2D\fP"
.br
.ti -1c
.RI "struct \fBVertex3D\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBsortfunc\fP (const \fBVertex3D\fP &lhs, const \fBVertex3D\fP &rhs)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "bool sortfunc (const \fBVertex3D\fP & lhs, const \fBVertex3D\fP & rhs)"

.PP
Definition at line 27 of file Vertex\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for COP290 from the source code\&.
