.TH "vertex3D" 3 "Thu Apr 5 2018" "COP290" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vertex3D \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <structs\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string \fBlabel\fP"
.br
.ti -1c
.RI "float \fBx\fP"
.br
.ti -1c
.RI "float \fBy\fP"
.br
.ti -1c
.RI "float \fBz\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 10 of file structs\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "std::string vertex3D::label"

.PP
Definition at line 12 of file structs\&.h\&.
.SS "float vertex3D::x"

.PP
Definition at line 13 of file structs\&.h\&.
.SS "float vertex3D::y"

.PP
Definition at line 14 of file structs\&.h\&.
.SS "float vertex3D::z"

.PP
Definition at line 15 of file structs\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for COP290 from the source code\&.
