.TH "vertex2D" 3 "Thu Apr 5 2018" "COP290" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vertex2D \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <structs\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string \fBlabel\fP"
.br
.ti -1c
.RI "float \fBx\fP"
.br
.ti -1c
.RI "float \fBy\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 3 of file structs\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "std::string vertex2D::label"

.PP
Definition at line 5 of file structs\&.h\&.
.SS "float vertex2D::x"

.PP
Definition at line 6 of file structs\&.h\&.
.SS "float vertex2D::y"

.PP
Definition at line 7 of file structs\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for COP290 from the source code\&.
